DynamicsNAV365-StaffPortal/Controllers/FinanceServices/ActivityRequestController.cs
using DynamicsNAV365_StaffPortal.Controllers.ResponseServices;
using DynamicsNAV365_StaffPortal.DynamicsNAVODataServiceReference;
using DynamicsNAV365_StaffPortal.Models.DocumentMgmt;
using DynamicsNAV365_StaffPortal.Models.Finance.FinanceHome;
using DynamicsNAV365_StaffPortal.Models.Finance.Imprest;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.SharePoint.Client;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Globalization;
using System.IO;
using System.Net;
using System.Security;
using System.Threading.Tasks;
using DynamicsNAV365_StaffPortal.Models;

namespace DynamicsNAV365_StaffPortal.Controllers.FinanceServices
{
    public class ActivityRequestController : Controller
    {
        static string companyURL = "";

        DynamicsNAVSOAPServices dynamicsNAVSOAPServices = new DynamicsNAVSOAPServices(companyURL);
        DynamicsNAVODATAServices dynamicsNAVODataServices = new DynamicsNAVODATAServices(companyURL);
        BCODATAServices _bcodataServices = new BCODATAServices(companyURL);

        SuccessResponseController successResponse = new SuccessResponseController();
        InfoResponseController infoResponse = new InfoResponseController();
        ErrorResponseController errorResponse = new ErrorResponseController();

        private string responseHeader = "";
        private string responseMessage = "";
        private string detailedResponseMessage = "";

        private string button1ControllerName = "";
        private string button1ActionName = "";
        private bool button1HasParameters = false;
        private string button1Parameters = "";
        private string button1Name = "";

        private string button2ControllerName = "";
        private string button2ActionName = "";
        private bool button2HasParameters = false;
        private string button2Parameters = "";
        private string button2Name = "";

        IQueryable<Currencies> currencyCodes = null;
        IQueryable<DimensionValues> globalDimension1Codes = null;
        IQueryable<DimensionValues> globalDimension2Codes = null;
        IQueryable<DimensionValues> shortcutDimension3Codes = null;
        IQueryable<DimensionValues> shortcutDimension4Codes = null;
        IQueryable<DimensionValues> shortcutDimension5Codes = null;
        IQueryable<DimensionValues> shortcutDimension6Codes = null;
        IQueryable<DimensionValues> shortcutDimension7Codes = null;
        IQueryable<DimensionValues> shortcutDimension8Codes = null;

        List<ImprestCategory> imprestCategoryList = null;

        AccountController accountController = new AccountController();
        string employeeNo = "";

        public ActivityRequestController()
        {
            employeeNo = AccountController.GetEmployeeNo();

        }

        #region New Imprest Request

        [Authorize]
        public ActionResult NewImprestRequest()
        {
            string openImprestNo = "";
            string imprestNo = "";

            try
            {
                ActivityRequestHeader imprestRequestObj = new ActivityRequestHeader();

                //if (dynamicsNAVSOAPServices.activityRequestWS.PreviousImprestSurrendered(employeeNo))
                //{
                //    return errorResponse.ApplicationError(responseHeader, responseMessage, detailedResponseMessage,
                //                                          button1ControllerName, button1ActionName, button1HasParameters, button1Parameters, button1Name,
                //                                          button2ControllerName, button2ActionName, button2HasParameters, button2Parameters, button2Name);
                //}

                //openImprestNo = dynamicsNAVSOAPServices.activityRequestWS.CheckOpenImprestRequestExists(employeeNo);

                ////Check open imprest request
                //if (!openImprestNo.Equals(""))
                //{
                //    responseHeader = "Open Activity Request";
                //    responseMessage = "An open activity request No. " + openImprestNo + " exists under your employee no. " + employeeNo + ", finalize on this imprest before creating a new one.";
                //    detailedResponseMessage = "An open activity request No. " + openImprestNo + " exists under your employee no. " + employeeNo + ", finalize on this imprest before creating a new one.";

                //    button1ControllerName = "ActivityRequest";
                //    button1ActionName = "ImprestRequestHistory";
                //    button1HasParameters = false;
                //    button1Parameters = "";
                //    button1Name = "Ok";

                //    button2ControllerName = "";
                //    button2ActionName = "";
                //    button2HasParameters = false;
                //    button2Parameters = "";
                //    button2Name = "";
                //    return errorResponse.ApplicationError(responseHeader, responseMessage, detailedResponseMessage,
                //                                          button1ControllerName, button1ActionName, button1HasParameters, button1Parameters, button1Name,
                //                                          button2ControllerName, button2ActionName, button2HasParameters, button2Parameters, button2Name);
                //}
                ////End check open imprest request

                //Create a new imprest request
                imprestNo = dynamicsNAVSOAPServices.activityRequestWS.CreateImprestHeader(employeeNo);
                //End create imprest request

                imprestRequestObj.No = imprestNo;
                imprestRequestObj.EmployeeNo = employeeNo;
                imprestRequestObj.EmployeeName = dynamicsNAVSOAPServices.employeeAccountWS.GetEmployeeName(employeeNo);
                imprestRequestObj.GlobalDimension1Code = "";

                //LoadCurrencies();
                //LoadImprestRequestDimensions(imprestRequestObj.GlobalDimension1Code);

                return View(imprestRequestObj);
            }
            catch (Exception ex)
            {
                return errorResponse.ApplicationExceptionError(ex);
            }
        }

        [Authorize]
        [HttpPost]
        public ActionResult NewImprestRequest(ActivityRequestHeader ImprestRequestObj)
        {
            bool imprestRequestModified = false;
            bool approvalWorkflowExist = false;

            try
            {
                //LoadCurrencies();
                //LoadImprestRequestDimensions(ImprestRequestObj.GlobalDimension1Code);

                if (ModelState.IsValid)
                {
                    if (dynamicsNAVSOAPServices.activityRequestWS.CheckImprestRequestExists(ImprestRequestObj.No, AccountController.GetEmployeeNo()))
                    {
                        //Check imprest lines
                        if (!dynamicsNAVSOAPServices.activityRequestWS.CheckImprestLinesExist(ImprestRequestObj.No))
                        {
                            ImprestRequestObj.ErrorStatus = true;
                            ImprestRequestObj.ErrorMessage = "Imprest lines missing, the imprest must contain a minimum of one imprest line, add an imprest line to continue.";
                            return View(ImprestRequestObj);
                        }
                        //Validate imprest lines
                        string imprestLineError = "";
                        imprestLineError = dynamicsNAVSOAPServices.activityRequestWS.ValidateImprestLines(ImprestRequestObj.No);
                        if (!imprestLineError.Equals(""))
                        {
                            ImprestRequestObj.ErrorStatus = true;
                            ImprestRequestObj.ErrorMessage = imprestLineError;
                            return View(ImprestRequestObj);
                        }

                        //Modify imprest request
                        ImprestRequestObj.Destination = ImprestRequestObj.Destination != null ? ImprestRequestObj.Destination : "";
                        ImprestRequestObj.DateFrom = ImprestRequestObj.DateFrom != "01/01/0001" ? ImprestRequestObj.DateFrom : DateTime.Now.ToString();
                        ImprestRequestObj.DateTo = ImprestRequestObj.DateTo != "01/01/0001" ? ImprestRequestObj.DateTo : DateTime.Now.ToString();

                        imprestRequestModified = dynamicsNAVSOAPServices.activityRequestWS.ModifyImprestHeader(ImprestRequestObj.No, ImprestRequestObj.EmployeeNo, ImprestRequestObj.Description, ImprestRequestObj.CreatePV);
                        if (!imprestRequestModified)
                        {
                            ImprestRequestObj.ErrorStatus = true;
                            ImprestRequestObj.ErrorMessage = "An error was experienced while trying to modify imprest no." + ImprestRequestObj.No + ", the server might be offline, try again after a while.";
                            return View(ImprestRequestObj);
                        }
                        //Send imprest for approval
                        approvalWorkflowExist = dynamicsNAVSOAPServices.activityRequestWS.CheckImprestApprovalWorkflowEnabled(ImprestRequestObj.No);
                        if (!approvalWorkflowExist)
                        {
                            ImprestRequestObj.ErrorStatus = true;
                            ImprestRequestObj.ErrorMessage = "An error was experienced while trying to send an approval request for imprest no." + ImprestRequestObj.No + ", the approval workflow was not found. " + ServiceConnection.contactICTDepartment + "";
                            return View(ImprestRequestObj);
                        }

                        if (dynamicsNAVSOAPServices.activityRequestWS.SendImprestApprovalRequest(ImprestRequestObj.No))
                        {
                            responseHeader = "Success";

DynamicsNAV365-StaffPortal/Views/ActivityRequest/ImprestApproval.cshtml
@model DynamicsNAV365_StaffPortal.Models.Finance.Imprest.ActivityRequestHeader

@{
    ViewBag.Title = "View Imprest Request";
}
<div class="wrapper row-offcanvas row-offcanvas-left">
    <!--Render Finance Sidebar-->
    @{Html.RenderAction("_FinanceSidebar", "FinanceHome");}
    <aside class="right-side">
        <section class="content">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        @using (Html.BeginForm("ImprestApproval", "Imprest", FormMethod.Post, new { @class = "" }))
                        {
                            @Html.AntiForgeryToken()
                            <div class="card-header" data-background-color="company_card">
                                <div class="row">
                                    <div class="col-md-4">
                                        <h5 class="title"><i><strong>Approve/Reject Imprest Request</strong></i></h5>
                                    </div>
                                    <div class="col-md-8">
                                       
                                        <div class="col-md-2">
                                            <input type="button" class="btn btn-warning btn-xs pull-right ladda-button" value="Activity Request Report" onclick="GenerateReport('@Model.No');" />
                                        </div>
                                        <div class="pull-right">
                                            <button type="submit" id="btnApprove" name="Command" value="Approve" class="btn btn-success btn-xs ladda-button" data-style="slide-right">
                                                <span class="ladda-label">
                                                    <i class="fa fa-check-circle"></i>
                                                    Approve
                                                </span>
                                            </button>
                                            <button type="submit" id="btnReject" name="Command" value="Reject" class="btn btn-danger btn-xs ladda-button" data-style="slide-right">
                                                <span class="ladda-label">
                                                    <i class="fa fa-close"></i>
                                                    Reject
                                                </span>
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="card-content">
                                @if (Model != null && Model.ErrorStatus == true)
                                {
                                    <div class="alert alert-danger">
                                        <strong>Error! </strong>@Html.Raw(HttpUtility.HtmlDecode(Model.ErrorMessage))
                                    </div>
                                }
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group label-floating">
                                            @Html.LabelFor(model => model.No, htmlAttributes: new { @id = "NoLbl", @class = "control-label" })
                                            @Html.EditorFor(model => model.No, new { htmlAttributes = new { @class = "form-control", @readonly = true } })
                                            @Html.ValidationMessageFor(model => model.No, "", new { @id = "NoError", @class = "text-danger" })
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group label-floating">
                                            @Html.LabelFor(model => model.EmployeeNo, htmlAttributes: new { @id = "EmployeeNoLbl", @class = "control-label" })
                                            @Html.EditorFor(model => model.EmployeeNo, new { htmlAttributes = new { @class = "form-control", @readonly = true } })
                                            @Html.ValidationMessageFor(model => model.EmployeeNo, "", new { @id = "EmployeeNoError", @class = "text-danger" })
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group label-floating">
                                            @Html.LabelFor(model => model.EmployeeName, htmlAttributes: new { @id = "EmployeeNameLbl", @class = "control-label" })
                                            @Html.EditorFor(model => model.EmployeeName, new { htmlAttributes = new { @class = "form-control", @readonly = true } })
                                            @Html.ValidationMessageFor(model => model.EmployeeName, "", new { @id = "EmployeeNameError", @class = "text-danger" })
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group label-floating">
                                            @Html.LabelFor(model => model.Amount, htmlAttributes: new { @id = "AmountLbl", @class = "control-label" })
                                            @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control", @readonly = true } })
                                            @Html.ValidationMessageFor(model => model.Amount, "", new { @id = "AmountError", @class = "text-danger" })
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group label-floating">
                                            @Html.LabelFor(model => model.Description, htmlAttributes: new { @id = "DescriptionLbl", @class = "control-label" })
                                            @{
                                                var description = Model?.Description;
                                                <input type="text" class="form-control" readonly="readonly" value="@description">
                                            }
                                            @*@Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control", @readonly = true } })
                                            @Html.ValidationMessageFor(model => model.Description, "", new { @id = "DescriptionError", @class = "text-danger" })*@
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            @Html.LabelFor(model => model.Comments, htmlAttributes: new { @id = "CommentsLbl", @class = "control-label" })
                                            @Html.EditorFor(model => model.Comments, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.Comments, "", new { @id = "CommentsError", @class = "text-danger" })
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            @Html.LabelFor(model => model.GlobalDimension2Code, htmlAttributes: new { @id = "GlobalDimension2CodeLbl", @class = "control-label" })
                                            @Html.EditorFor(model => model.GlobalDimension2Code, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.GlobalDimension2Code, "", new { @id = "GlobalDimension2CodeError", @class = "text-danger" })
                                        </div>
                                    </div>
                                </div>
                            </div>
                        }
                        <div class="card-footer">
                            <div class="row">
                                <div class="col-md-12">
                                    <!--Render imprest line partial view-->
                                    @{Html.RenderAction("_ImprestLine", "ActivityRequest", new { ImprestNo = Model.No });}
                                </div>
                            </div>
                            <hr />
                            <div class="row">
                                <div class="col-md-12">
                                    <div id="divAttachDocs"></div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <a class="btn btn-danger pull-right" href="@Url.Action("OpenEntries", "Approval")">
                                        <i class="fa fa-close"></i>
                                        Close
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </aside>
</div>
@section scripts{
    <script src="~/Scripts/Finance/ImprestRequestScripts/ImprestRequest.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            //Add CSS Classes
            $("#ImprestRequestHistoryMenuItem").addClass("active");

        	//Load dimensions
          //  LoadDimensionValues();

        	//Initialize Imprest Scripts
            InitializeImprestRequest();

            var DocumentNo = $("#No").val();
            LoadImprestLines(DocumentNo);
            LoadImprestDocuments(DocumentNo);

        });
        var GenerateReport = function (DocNo) {
            $.ajax({
                async: true,
                type: "POST",
                datatype: "json",
                contentType: "application/json; charset = utf-8",
                processData: false,
                data: JSON.stringify({ DocNo: DocNo }),

                url: '/ActivityRequest/GenerateReport',
                success: function (data) {
                    window.open(data.message, '_blank').focus();
                    //window.alert(data.message);
                    //window.location.reload();
                },
                error: function () {
                    window.alert(data.message);
                }
            });
        };
    </script>
}

DynamicsNAV365-StaffPortal/Views/ActivityRequest/ImprestRequestHistory.cshtml
@model IList<DynamicsNAV365_StaffPortal.Models.Finance.Imprest.ActivityRequestHeader>

@{
    ViewBag.Title = "Activity Requests";
}
<div class="wrapper row-offcanvas row-offcanvas-left">
    <!--Render Finance Sidebar-->
    @{Html.RenderAction("_FinanceSidebar", "FinanceHome");}
    <aside class="right-side">
        <section class="content">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header" data-background-color="company_card">
                            <div class="row">
                                <div class="col-md-4">
                                    <h4 class="title"><i>Activity Requests</i></h4>
                                </div>
                                <div class="col-md-8">
                                    <a class="btn btn-white btn-xs pull-right" href="@Url.Action("NewImprestRequest", "ActivityRequest")" data-background-color="login_card">
                                        <strong style="color:white">
                                            <i class="fa fa-plus"></i>
                                            New Activity Request
                                        </strong>
                                    </a>
                                </div>
                            </div>
                        </div>
                        <div class="card-content">
                            <div class="row">
                                <div class="col-md-12">
                                    <div id="TableContainer" class="table-responsive">
                                        <table id="ImprestListTbl" class="stripe">
                                            <thead class="text-primary">
                                                <tr>
                                                    <th>No.</th>
                                                    <th>Document Date</th>
                                                    <th>Currency</th>
                                                    <th>Amount</th>
                                                    <th>Date From</th>
                                                    <th>Date To</th>
                                                    <th>Description</th>
                                                    <th>Comments</th>
                                                    <th>Status</th>
                                                    <th>&nbsp;</th>
                                                    <th>&nbsp;</th>
                                                    <th>&nbsp;</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                @{		string editUrl = "";
                                                    string viewUrl = "";
                                                    string approverUrl = "";
                                                    for (int i = 0; i < Model.Count; i++)
                                                    {
                                                        editUrl = Url.Action("OnBeforeEdit", "ActivityRequest") + "?ImprestNo=" + Model[i].No;
                                                        viewUrl = Url.Action("ViewImprestRequest", "ActivityRequest") + "?ImprestNo=" + Model[i].No;
                                                        approverUrl = Url.Action("Approvals", "Approval") + "?DocumentNo=" + Model[i].No;
                                                        <tr>
                                                            <td>@Model[i].No</td>
                                                            <td>@Model[i].DocumentDate</td>
                                                            <td>@Model[i].CurrencyCode</td>
                                                            <td>@Model[i].Amount</td>
                                                            <td>@Model[i].DateFrom</td>
                                                            <td>@Model[i].DateTo</td>
                                                            <td>@Model[i].Description</td>
                                                            <td>@Model[i].Comments</td>
                                                            <td>@Model[i].Status</td>
                                                            <td>
                                                                @if (@Model[i].Status == "Open" || @Model[i].Status == "Declined with amendments")
                                                                {
                                                                    <a href="@editUrl" class=""><b>Edit</b></a>
                                                                }
                                                            </td>
                                                            <td>
                                                                <a href="@viewUrl" class=""><b>View</b></a>
                                                            </td>
                                                            <td>
                                                                <a href="@approverUrl" style="color:red" class="fa fa-check"><b>Approval Workflow</b></a>
                                                            </td>
                                                        </tr>
}
                                                }
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="card-footer">

                        </div>
                    </div>
                </div>
            </div>
        </section>
    </aside>
</div>
@section scripts{
    <script type="text/javascript">
        $(document).ready(function () {
            //Add CSS Classes
            $("#ImprestRequestHistory").addClass("active");

        	$("#ImprestListTbl").dataTable({
                "order": [[0, "No"]],
                "columnDefs": [ {
                    "targets": [1,2,3,4,5,6,7,8,9,10],
                    "orderable": false,
                }],

                "fixedColumns": true
            });
        });
    </script>
}