DynamicsNAV365-StaffPortal/Models/Approvals/ApprovalEntryModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DynamicsNAV365_StaffPortal.Models.Approvals
{
	public class ApprovalEntryModel
	{
		public string EntryNo { get; set; }
		public string TableID { get; set; }
		public string DocumentType { get; set; }
		public string DocumentNo { get; set; }
		public string Description { get; set; }
		public string SequenceNo { get; set; }
		public string ApprovalCode { get; set; }
		public string SenderEmployeeNo { get; set; }
		public string SenderEmployeeName { get; set; }
		public string ApproverEmployeeNo { get; set; }
		public string ApproverEmployeeName { get; set; }
		public string SenderID { get; set; }
		public string ApproverID { get; set; }
		public string Status { get; set; }
		public string DateTimeSentforApproval { get; set; }
		public string Comment { get; set; }
		public string DueDate { get; set; }
		public string Amount { get; set; }
		public string CurrencyCode { get; set; }
		public bool ErrorStatus { get; set; }
		public string ErrorMessage { get; set; }
        public string ImprestType { get; set; }
    }
}

DynamicsNAV365-StaffPortal/Controllers/ApprovalServices/ApprovalController.cs
using DynamicsNAV365_StaffPortal.Controllers.ResponseServices;
using DynamicsNAV365_StaffPortal.DynamicsNAVODataServiceReference;
using DynamicsNAV365_StaffPortal.Models.Account;
using DynamicsNAV365_StaffPortal.Models.Approvals;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DynamicsNAV365_StaffPortal.Controllers.ApprovalServices
{
    public class ApprovalController : Controller
    {
		string companyName = ServiceConnection.CompanyName;
		static string companyURL = "";

		DynamicsNAVSOAPServices dynamicsNAVSOAPServices = new DynamicsNAVSOAPServices(companyURL);
		DynamicsNAVODATAServices dynamicsNAVODataServices = new DynamicsNAVODATAServices(companyURL);
        BCODATAServices _bcodataServices = new BCODATAServices(companyURL);

        SuccessResponseController successResponse = new SuccessResponseController();
		InfoResponseController infoResponse = new InfoResponseController();
		ErrorResponseController errorResponse = new ErrorResponseController();

		AccountController accountController = new AccountController();
		string employeeNo = "";

		public ApprovalController()
		{
			employeeNo = AccountController.GetEmployeeNo();
		}

        [Authorize]
        public ActionResult Approvals(string DocumentNo)
        {
            try
            {
                List<ApprovalEntryModel> approvalEntriesList = new List<ApprovalEntryModel>();

                dynamic approvalEntries = JsonConvert.DeserializeObject(dynamicsNAVSOAPServices.ApprovalsMgmt.GetApprovers("", DocumentNo));

                foreach (var approvalEntry in approvalEntries)
                {
                    ApprovalEntryModel approvalEntryObj = new ApprovalEntryModel();
                    approvalEntryObj.EntryNo = approvalEntry.EntryNo;
                    approvalEntryObj.TableID = approvalEntry.TableID;
                    approvalEntryObj.DocumentType = approvalEntry.DocumentType;
                    approvalEntryObj.DocumentNo = approvalEntry.DocumentNo;
                    approvalEntryObj.Description = approvalEntry.Description;
                    approvalEntryObj.SequenceNo = approvalEntry.SequenceNo;
                    approvalEntryObj.ApprovalCode = approvalEntry.ApprovalCode;
                    approvalEntryObj.SenderID = approvalEntry.SenderID;
                    approvalEntryObj.ApproverID = approvalEntry.ApproverID;
                    approvalEntryObj.Status = approvalEntry.Status;
                    approvalEntryObj.DateTimeSentforApproval = approvalEntry.DateTimeSentforApproval;
                    approvalEntryObj.Amount = approvalEntry.Amount;
                    approvalEntryObj.CurrencyCode = approvalEntry.CurrencyCode;
                    approvalEntryObj.ApproverEmployeeNo = approvalEntry.ApproverEmployeeNo;
                    approvalEntryObj.ApproverEmployeeName = approvalEntry.ApproverEmployeeName;
                    approvalEntryObj.SenderEmployeeNo = approvalEntry.SenderEmployeeNo;
                    approvalEntryObj.SenderEmployeeName = approvalEntry.SenderEmployeeName;
                    approvalEntriesList.Add(approvalEntryObj);
                }
                return View(approvalEntriesList);
            }
            catch (Exception ex)
            {
                return errorResponse.ApplicationExceptionError(ex);
            }
        }

        [Authorize]
        public ActionResult OpenEntries()
        {
            try
            {
                List<ApprovalEntryModel> approvalEntriesList = new List<ApprovalEntryModel>();

                var useremployee = _bcodataServices.BCOData.UserSetupQuery.Execute().ToList();
                var employeeuser = useremployee.Where(c => c.Employee_No == employeeNo).FirstOrDefault()?.User_ID;

                //if (employeeuser != null)
                //{
                //    approvalEntryObj.ErrorStatus = true;
                //    approvalEntryObj.ErrorMessage =
                //        "Kindly provide reason (s) for declining/rejecting this document.";
                //}

                dynamic approvalEntries = JsonConvert.DeserializeObject(dynamicsNAVSOAPServices.ApprovalsMgmt.GetOpenApprovalEntries(employeeuser, ""));

                foreach (var approvalEntry in approvalEntries)
                {
                    ApprovalEntryModel approvalEntryObj = new ApprovalEntryModel();
                    approvalEntryObj.EntryNo = approvalEntry.EntryNo;
                    approvalEntryObj.TableID = approvalEntry.TableID;
                    approvalEntryObj.DocumentType = approvalEntry.DocumentType;
                    approvalEntryObj.DocumentNo = approvalEntry.DocumentNo;
                    approvalEntryObj.Description = approvalEntry.Description;
                    approvalEntryObj.SequenceNo = approvalEntry.SequenceNo;
                    approvalEntryObj.ApprovalCode = approvalEntry.ApprovalCode;
                    approvalEntryObj.SenderID = approvalEntry.SenderID;
                    approvalEntryObj.ApproverID = approvalEntry.ApproverID;
                    approvalEntryObj.Status = approvalEntry.Status;
                    approvalEntryObj.DateTimeSentforApproval = approvalEntry.DateTimeSentforApproval;
                    approvalEntryObj.Amount = approvalEntry.Amount;
                    approvalEntryObj.CurrencyCode = approvalEntry.CurrencyCode;
                    approvalEntryObj.ApproverEmployeeNo = approvalEntry.ApproverEmployeeNo;
                    approvalEntryObj.ApproverEmployeeName = approvalEntry.ApproverEmployeeName;
                    approvalEntryObj.SenderEmployeeNo = approvalEntry.SenderEmployeeNo;
                    approvalEntryObj.SenderEmployeeName = approvalEntry.SenderEmployeeName;
                    approvalEntryObj.ImprestType = approvalEntry.ImprestType;
                    approvalEntriesList.Add(approvalEntryObj);
                }

                return View(approvalEntriesList);
            }
            catch (Exception ex)
            {
                return errorResponse.ApplicationExceptionError(ex);
            }
        } 

        [Authorize]
        public ActionResult RejectedEntries() 
        {
            try
            {
                List<ApprovalEntryModel> approvalEntriesList = new List<ApprovalEntryModel>();

                dynamic approvalEntries = JsonConvert.DeserializeObject(dynamicsNAVSOAPServices.ApprovalsMgmt.GetRejectedApprovalEntries(employeeNo, ""));

                foreach (var approvalEntry in approvalEntries)
                {
                    ApprovalEntryModel approvalEntryObj = new ApprovalEntryModel();
                    approvalEntryObj.EntryNo = approvalEntry.EntryNo;
                    approvalEntryObj.TableID = approvalEntry.TableID;
                    approvalEntryObj.DocumentType = approvalEntry.DocumentType;
                    approvalEntryObj.DocumentNo = approvalEntry.DocumentNo;
                    approvalEntryObj.Description = approvalEntry.Description;
                    approvalEntryObj.SequenceNo = approvalEntry.SequenceNo;
                    approvalEntryObj.ApprovalCode = approvalEntry.ApprovalCode;
                    approvalEntryObj.SenderID = approvalEntry.SenderID;
                    approvalEntryObj.ApproverID = approvalEntry.ApproverID;
                    approvalEntryObj.Status = approvalEntry.Status;
                    approvalEntryObj.DateTimeSentforApproval = approvalEntry.DateTimeSentforApproval;
                    approvalEntryObj.Amount = approvalEntry.Amount;
                    approvalEntryObj.CurrencyCode = approvalEntry.CurrencyCode;
                    approvalEntryObj.ApproverEmployeeNo = approvalEntry.ApproverEmployeeNo;
                    approvalEntryObj.ApproverEmployeeName = approvalEntry.ApproverEmployeeName;
                    approvalEntryObj.SenderEmployeeNo = approvalEntry.SenderEmployeeNo;
                    approvalEntryObj.SenderEmployeeName = approvalEntry.SenderEmployeeName;
                    approvalEntriesList.Add(approvalEntryObj);
                }

                return View(approvalEntriesList);
            }
            catch (Exception ex)
            {
                return errorResponse.ApplicationExceptionError(ex);
            }
        }

        [Authorize]
        public ActionResult ApprovedEntries() 
        {
            try
            {
                List<ApprovalEntryModel> approvalEntriesList = new List<ApprovalEntryModel>();

                dynamic approvalEntries = JsonConvert.DeserializeObject(dynamicsNAVSOAPServices.ApprovalsMgmt.GetApprovedApprovalEntries(employeeNo, ""));

                foreach (var approvalEntry in approvalEntries)
                {
                    ApprovalEntryModel approvalEntryObj = new ApprovalEntryModel();
                    approvalEntryObj.EntryNo = approvalEntry.EntryNo;
                    approvalEntryObj.TableID = approvalEntry.TableID;
                    approvalEntryObj.DocumentType = approvalEntry.DocumentType;
                    approvalEntryObj.DocumentNo = approvalEntry.DocumentNo;
                    approvalEntryObj.Description = approvalEntry.Description;
                    approvalEntryObj.SequenceNo = approvalEntry.SequenceNo;
                    approvalEntryObj.ApprovalCode = approvalEntry.ApprovalCode;
                    approvalEntryObj.SenderID = approvalEntry.SenderID;
                    approvalEntryObj.ApproverID = approvalEntry.ApproverID;
                    approvalEntryObj.Status = approvalEntry.Status;
                    approvalEntryObj.DateTimeSentforApproval = approvalEntry.DateTimeSentforApproval;
                    approvalEntryObj.Amount = approvalEntry.Amount;
                    approvalEntryObj.CurrencyCode = approvalEntry.CurrencyCode;
                    approvalEntryObj.ApproverEmployeeNo = approvalEntry.ApproverEmployeeNo;

DynamicsNAV365-StaffPortal/Views/Approval/Approvals.cshtml
@model IList<DynamicsNAV365_StaffPortal.Models.Approvals.ApprovalEntryModel>

@{
	ViewBag.Title = "Approvers";
}
<div class="wrapper row-offcanvas row-offcanvas-left">
	<!--Render Approval Sidebar-->
	@{Html.RenderAction("_ApprovalSidebar", "Approval");}
	<aside class="right-side">
		<section class="content">
			<div class="row">
				<div class="col-md-12">
					<div class="card">
						<div class="card-header" data-background-color="company_card">
							<div class="row">
								<div class="col-md-4">
									<h4 class="title"><i>Approval Workflow</i></h4>
								</div>
								<div class="col-md-8">
									<a class="btn btn-danger btn-xs pull-right" href="@Url.Action("Index", "Home")">
										<i class="fa fa-close"></i>
										Close
									</a>
								</div>
							</div>
						</div>
						<div class="card-content">
							<div class="row">
								<div class="col-md-12">
									<div id="TableContainer" class="table-responsive">
										<table id="ApprovalTbl" class="stripe">
											<thead class="text-primary">
												<tr>
													<th>Document No.</th>
													<th>Sequence No.</th>
													<th>Approver Name </th>
													<th>Status</th>
													<th>Date Sent for Approval</th>
												</tr>
											</thead>
											<tbody>
												@{				
													string viewUrl = "";
													for (int i = 0; i < Model.Count; i++)
													{
														viewUrl = Url.Action("Approvals", "Approval") + "?DocumentNo=" + Model[i].DocumentNo;
														<tr>
															<td>@Model[i].DocumentNo</td>
															<td>@Model[i].SequenceNo</td>
															<td>@Model[i].ApproverID</td>
															<td>@Model[i].Status</td>
															<td>@Model[i].DateTimeSentforApproval</td>
														</tr>		
													}
												}
											</tbody>
										</table>
									</div>
								</div>
							</div>
						</div>
						<div class="card-footer">

						</div>
					</div>
				</div>
			</div>
		</section>
	</aside>

</div>
@section scripts{
	<script type="text/javascript">
        $(document).ready(function () {
            //Add CSS Classes
            $("#RequestsToApprovalMenuItem").addClass("active");

            $("#ApprovalTbl").dataTable({
            	"order": [[0, "DocumentNo"]],
            	"columnDefs": [{
            		"targets": [1,2,3,4],
            		"orderable": false,
            	}],

            	"fixedColumns": true
            });
        });
	</script>
}

DynamicsNAV365-StaffPortal/Views/Approval/ApprovedEntries.cshtml
@model IList<DynamicsNAV365_StaffPortal.Models.Approvals.ApprovalEntryModel>

@{
    ViewBag.Title = "Approved Requests";
}
<div class="wrapper row-offcanvas row-offcanvas-left">
    <!--Render Approval Sidebar-->
    @{Html.RenderAction("_ApprovalSidebar", "Approval");}
    <aside class="right-side">
        <section class="content">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header" data-background-color="company_card">
                            <div class="row">
                                <div class="col-md-4">
                                    <h4 class="title"><i>Approved Requests</i></h4>
                                </div>
                            </div>
                        </div>
                        <div class="card-content">
                            <div class="row">
                                <div class="col-md-12">
                                    <div id="TableContainer" class="table-responsive">
                                        <table id="RequestsToApprovalTbl" class="stripe">
                                            <thead class="text-primary">
                                                <tr>
                                                    <th>Document Type</th>
                                                    <th>Document No.</th>
                                                    <th>Description</th>
                                                    <th>Quantity</th>
                                                    <th>Status</th>
                                                    <th>ApprovalrequestDate</th>
                                                    <th>SenderName</th>
                                                    <th>ApproverName</th>
                                                    @*<th>&nbsp;</th>*@
                                                </tr>
                                            </thead>
                                            <tbody>
                                                @{
                                                    string viewUrl = "";
                                                    for (int i = 0; i < Model.Count; i++)
                                                    {
                                                        switch (Model[i].TableID)
                                                        {
                                                            //Finance Approval
                                                            case "51535008": viewUrl = Url.Action("ImprestApproval", "Imprest") + "?ImprestNo=" + Model[i].DocumentNo; break;
                                                            case "51535010": viewUrl = Url.Action("ImprestSurrenderApproval", "ImprestSurrender") + "?ImprestSurrenderNo=" + Model[i].DocumentNo; break;
                                                            case "51535012": viewUrl = Url.Action("FundsClaimApproval", "FundsClaim") + "?DocumentNo=" + Model[i].DocumentNo; break;
                                                            case "51525003":
                                                                switch (Model[i].DocumentType)
                                                                {
                                                                    case "Imprest": viewUrl = Url.Action("ImprestApproval", "Imprest") + "?ImprestNo=" + Model[i].DocumentNo; break;
                                                                    case "Imprest Surrender": viewUrl = Url.Action("ImprestSurrenderApproval", "ImprestSurrender") + "?ImprestSurrenderNo=" + Model[i].DocumentNo; break;
                                                                    case "PettyCash": viewUrl = Url.Action("PettyCashApproval", "PettyCash") + "?PettyCashNo=" + Model[i].DocumentNo; break;
                                                                    case "PettyCash Surrender": viewUrl = Url.Action("PettyCashSurrenderApproval", "PettyCashSurrender") + "?PettyCashSurrenderNo=" + Model[i].DocumentNo; break;
                                                                    case "Claim/Refund": viewUrl = Url.Action("ClaimsRefundApproval", "ClaimsRefund") + "?ClaimsRefundNo=" + Model[i].DocumentNo; break;
                                                                }
                                                                break;
                                                            //End Finance Approval

                                                            //Procurement Approval
                                                            case "51535080": viewUrl = Url.Action("PurchaseRequisitionApproval", "PurchaseRequisition") + "?PurchaseRequisitionNo=" + Model[i].DocumentNo; break;
                                                            case "38":
                                                                switch (Model[i].DocumentType)
                                                                {
                                                                    case "Order": viewUrl = Url.Action("PurchaseOrderApproval", "PurchaseOrder") + "?PurchaseOrderNo=" + Model[i].DocumentNo; break;
                                                                    case "Invoice": viewUrl = Url.Action("PurchaseInvoiceApproval", "PurchaseInvoice") + "?PurchaseInvoiceNo=" + Model[i].DocumentNo; break;
                                                                }
                                                                break;

                                                            //Stores Approval
                                                            case "51535140": viewUrl = Url.Action("StoreRequisitionApproval", "StoreRequisition") + "?StoreRequisitionNo=" + Model[i].DocumentNo; break;

                                                            //End Procurement Approval

                                                            //Human Resource Approval
                                                            case "51525209": viewUrl = Url.Action("LeaveApplicationApproval", "LeaveApplication") + "?LeaveApplicationNo=" + Model[i].DocumentNo; break;
                                                            case "51535265": viewUrl = Url.Action("TrainingNeedApproval", "EmployeeTraining") + "?TrainingNeedNo=" + Model[i].DocumentNo; break;
                                                            case "51535266": viewUrl = Url.Action("TrainingApplicationApproval", "EmployeeTraining") + "?ApplicationNo=" + Model[i].DocumentNo; break;
                                                            case "51535268": viewUrl = Url.Action("TrainingEvaluationApprovals", "EmployeeTraining") + "?EvaluationNo=" + Model[i].DocumentNo; break;
                                                            //End Human Resource Approval

                                                            //Fleet Management Approval
                                                            case "52137185": viewUrl = Url.Action("VehicleRequisitionApproval", "VehicleRequisition") + "?VehicleRequisitionNo=" + Model[i].DocumentNo; break;
                                                                //End Fleet Management Approval
                                                        }
                                                        <tr>
                                                            <td>@Model[i].DocumentType</td>
                                                            <td>@Model[i].DocumentNo</td>
                                                            <td>@Model[i].Description</td>
                                                            <td>@Model[i].Amount</td>
                                                            <td>@Model[i].Status</td>
                                                            <td>@Model[i].DateTimeSentforApproval</td>
                                                            <td>@Model[i].SenderEmployeeName</td>
                                                            <td>@Model[i].ApproverEmployeeName</td>
                                                            @*<td>
                                                                <a href="@viewUrl" class="btn btn-primary btn-xs"><i class="fa fa-sticky-note-o"></i>Open Record</a>
                                                            </td>*@
                                                        </tr>

                                                    }
                                                }
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="card-footer">

                        </div>
                    </div>
                </div>
            </div>
        </section>
    </aside>
</div>
@section scripts{
    <script type="text/javascript">
        $(document).ready(function () {
            //Add CSS Classes
            $("#ApprovedEntries").addClass("active");

            $("#RequestsToApprovalTbl").dataTable({
            	"order": [[0, "No"]],
            	"columnDefs": [{
            		"targets": [1,2,3,4,5,6,7],
            		"orderable": false,
            	}],

            	"fixedColumns": true
            });
        });
    </script>
}

DynamicsNAV365-StaffPortal/Views/Approval/_ApprovalSidebar.cshtml
@model DynamicsNAV365_StaffPortal.Models.Account.EmployeeProfileModel
<aside class="left-side sidebar-offcanvas">
	<section class="sidebar">
        <a href="@Url.Action("EmployeeProfile", "Account")">
            <div class="user-panel">
                <div class="pull-left image">
                    @if (Model != null && Model.PassportAttached == true)
                    {
                        <img src="~/EmployeeData/@Model.EmployeePassportPath" class="img-circle" alt="User Image" style="width: 103.5%;" />
                    }
                    else
                    {
                        <img src="~/Content/images/photo_placeholder.png" class="img-circle" alt="User Image" style="width: 103.5%;" />
                    }
                </div>
                <div class="pull-left info">
                    <p>@HttpContext.Current.User.Identity.Name</p>
                    <div class="online-status" style="font-size: 10px;">
                        <span class="fa fa-circle text-success" style="vertical-align: middle;"></span>
                        <span class="status-text" style="vertical-align: middle;">Online</span>
                    </div>
                </div>
            </div>
        </a>
        <ul class="sidebar-menu">
            <li>
                <a href="@Url.Action("Index", "Home")">
                    <i class="fa fa-dashboard"></i> <span>Dashboard</span>
                </a>
            </li>
            <li id="OpenEntries">
                <a href="@Url.Action("OpenEntries", "Approval")">
                    <i class="fa fa-circle-o"></i> <span>Requests To Approve</span>
                </a>
            </li>
            <li id="RejectedEntries">
                <a href="@Url.Action("RejectedEntries", "Approval")">
                    <i class="fa fa-window-close-o"></i> <span>Rejected Requests</span>
                </a>
            </li>
            <li id="ApprovedEntries">
                <a href="@Url.Action("ApprovedEntries", "Approval")">
                    <i class="fa fa-check-square-o"></i> <span>Approved Requests</span>
                </a>
            </li>
        </ul>
	</section>
</aside>