DynamicsNAV365-StaffPortal/Controllers/PayrollServices/EmployeeP9Controller.cs
using DynamicsNAV365_StaffPortal.Controllers.ResponseServices;
using DynamicsNAV365_StaffPortal.Models.PayrollModels;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace DynamicsNAV365_StaffPortal.Controllers.PayrollServices
{
    public class EmployeeP9Controller : Controller
    {
        string companyName = ServiceConnection.CompanyName;
        static string companyURL = "";

        DynamicsNAVSOAPServices dynamicsNAVSOAPServices = new DynamicsNAVSOAPServices(companyURL);
        DynamicsNAVODATAServices dynamicsNAVODataServices = new DynamicsNAVODATAServices(companyURL);
        BCODATAServices BCODATAServices = new BCODATAServices(companyURL);

        SuccessResponseController successResponse = new SuccessResponseController();
        InfoResponseController infoResponse = new InfoResponseController();
        ErrorResponseController errorResponse = new ErrorResponseController();

        AccountController accountController = new AccountController();
        string employeeNo = "";

        public EmployeeP9Controller()
        {
            employeeNo = AccountController.GetEmployeeNo();
        }

        #region  Employee P9

        [Authorize]
        public ActionResult PrintEmployeeP9()
        {
            try
            {
                EmployeeP9Model employeePayslipObj = new EmployeeP9Model();

                var payrollPeriods = from payrollPeriodQuery in BCODATAServices.BCOData.PayrollPeriods
                                     select payrollPeriodQuery;

                employeePayslipObj.EmployeeNo = AccountController.GetEmployeeNo();
                employeePayslipObj.PayrollPeriods = new SelectList(payrollPeriods, "Starting_Date", "Starting_Date");

                return View(employeePayslipObj);
            }
            catch (Exception ex)
            {
                return errorResponse.ApplicationExceptionError(ex);
            }
        }

        [HttpPost]
        [Authorize]
        public async Task<ActionResult> PrintEmployeeP9(EmployeeP9Model EmployeePayslipObj)
        {
            string filePath = "";
            if (ModelState.IsValid)
            {
                try
                {
                    var payrollPeriods = from payrollPeriodQuery in dynamicsNAVODataServices.dynamicsNAVOData.PayrollPeriods
                                         select payrollPeriodQuery;

                    EmployeePayslipObj.PayrollPeriods = new SelectList(payrollPeriods, "Starting_Date", "Starting_Date");
                    EmployeePayslipObj.EmployeeNo = AccountController.GetEmployeeNo();

                    filePath = dynamicsNAVSOAPServices.payrollManagementWS.GenerateP9(employeeNo, DateTime.Parse(EmployeePayslipObj.StartDate), DateTime.Parse(EmployeePayslipObj.EndDate), "");

                    if (!filePath.Equals(""))
                    {
                        using (WebClient wc = new WebClient())
                        {
                            var byteArr = await wc.DownloadDataTaskAsync(filePath);
                            return File(byteArr, "application/pdf");
                        }
                    }
                    else
                    {
                        EmployeePayslipObj.ErrorStatus = true;
                        EmployeePayslipObj.ErrorMessage = "Unable to print the payslip. " + ServiceConnection.contactICTDepartment + " ";

                        return View(EmployeePayslipObj);
                    }
                }
                catch (Exception ex)
                {
                    return errorResponse.ApplicationExceptionError(ex);
                }
            }
            else
            {
                return View(EmployeePayslipObj);
            }

        }

        [AcceptVerbs(HttpVerbs.Post)]
        public JsonResult GenerateP9(string StartDate, string EndDate)
        {
            try
            {
                string employeeNo = "";
                string filename = "";
                string filenane = "";
                employeeNo = AccountController.GetEmployeeNo();
                filename = "P9_" + employeeNo + ".pdf";

                filenane = dynamicsNAVSOAPServices.payrollManagementWS.GenerateP9(employeeNo, DateTime.Parse(StartDate), DateTime.Parse(EndDate), filename);
                return Json(new { message = $"{GetBaseUrl()}/reports/" + filename, success = true }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { message = ex.Message.Replace("'", ""), success = false }, JsonRequestBehavior.AllowGet);
            }
        }
        public string GetBaseUrl()
        {
            var request = HttpContext.Request;
            var appUrl = HttpRuntime.AppDomainAppVirtualPath;

            if (appUrl != "/") 
                appUrl = "/" + appUrl;

            var baseUrl = $"{request.Url?.Scheme}://{request.Url?.Authority}{appUrl}";

            return baseUrl;
        }


        #endregion End Employee P9

    }
}

DynamicsNAV365-StaffPortal/Views/EmployeeP9/PrintEmployeeP9.cshtml
@model DynamicsNAV365_StaffPortal.Models.PayrollModels.EmployeeP9Model
@{
    ViewBag.Title = "Employee P9";
}
<div class="wrapper row-offcanvas row-offcanvas-left">
    <!--Render Payroll Sidebar-->
    @{Html.RenderAction("_PayrollSidebar", "PayrollHome");}
    <aside class="right-side">
        <section class="content">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header" data-background-color="company_card">
                            <h4 class="title"><i>Employee P9</i></h4>
                        </div>
                        @using (Html.BeginForm("PrintEmployeeP9", "EmployeeP9", FormMethod.Post, new { @class = "" }))
                        {
                            @Html.AntiForgeryToken()
                            <div class="card-content">
                                @if (Model != null && Model.ErrorStatus == true)
                                {
                                    <div class="alert alert-danger">
                                        <strong>Error! </strong>@Html.Raw(HttpUtility.HtmlDecode(Model.ErrorMessage))
                                    </div>
                                }
                                @Html.HiddenFor(model => model.EmployeeNo)
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group label-floating">
                                            @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @id = "EndDateLbl", @class = "control-label" })
                                            @Html.DropDownListFor(model => model.StartDate, Model.PayrollPeriods, "", new { @class = "form-control" })
                                            @Html.ValidationMessageFor(model => model.StartDate, "", new { @id = "EndDateError", @class = "text-danger" })
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group label-floating">
                                            @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @id = "EndDateLbl", @class = "control-label" })
                                            @Html.DropDownListFor(model => model.EndDate, Model.PayrollPeriods, "", new { @class = "form-control" })
                                            @Html.ValidationMessageFor(model => model.EndDate, "", new { @id = "EndDateError", @class = "text-danger" })
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="card-footer">
                                <div class="row">
                                    <div class="col-md-7">
                                        <input type="button" class="btn btn-xs pull-right ladda-button" value="Preview P9 Report" onclick="GenerateP9();" />
                                        @*<button class="btn btn-xs pull-right ladda-button" type="submit" formtarget="_blank" data-style="slide-right" data-background-color="login_card">
                                            <span class="ladda-label">
                                                <i class="fa fa-print"></i>
                                                Preview P9
                                            </span>
                                        </button>*@
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </section>
    </aside>
</div>
@section scripts{
    <script type="text/javascript">
        $(document).ready(function () {
            //Add CSS Classes
            $("#PrintEmployeeP9").addClass("active");
            window.onblur = function () {
                Ladda.stopAll();
            }
        });
        var GenerateP9 = function () {
            var StartDate = $("#StartDate").val();
            var EndDate = $("#EndDate").val();
            $.ajax({
                async: true,
                type: "POST",
                datatype: "json",
                contentType: "application/json; charset = utf-8",
                processData: false,
                data: JSON.stringify({ StartDate: StartDate, EndDate: EndDate }),

                url: '@Url.Action("GenerateP9")',
                success: function (data) {
                    window.open(data.message, '_blank').focus();
                    //window.alert(data.message);
                    //window.location.reload();
                }
            });
        };
    </script>
}